apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "telegram-bot.fullname" . }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
rules:
# Pod operations
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create", "get"]
# Deployment operations
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch", "update"]
# Service operations
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Namespace operations
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
# Node operations (for cluster status)
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# ReplicaSet operations (for deployment management)
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# Events (for troubleshooting)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# Subresources for comprehensive access
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
# MachineSet operations (OpenShift)
- apiGroups: ["machine.openshift.io"]
  resources: ["machinesets"]
  verbs: ["get", "list", "watch", "patch", "update"]