{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app: {{ include "telegram-bot.name" . }}
    version: {{ .Chart.AppVersion }}
    {{- include "telegram-bot.labels" . | nindent 4 }}
{{- end }}