apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telegram-bot.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.botToken }}
  bot-token: {{ .Values.secrets.botToken | toString | b64enc }}
  {{- else }}
  bot-token: {{ "YOUR_BOT_TOKEN_HERE" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.authorizedUsers }}
  authorized-users: {{ .Values.secrets.authorizedUsers | toString | b64enc }}
  {{- else }}
  authorized-users: {{ "123456789" | b64enc }}
  {{- end }}