apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegram-bot.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "telegram-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.health.port }}
    protocol: TCP
    name: health
  selector:
    {{- include "telegram-bot.selectorLabels" . | nindent 4 }}